### ISSUE TITLE
Exception in thread Thread-80

### ISSUE THREAD

**Issue by JoKerTanser** [HIM049/MCDR_HibernateR#6]
Exception in thread Thread-80 (check_config_fire):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\HibernateR.v1.2.0.mcdr\hibernate_r\__init__.py", line 263, in check_config_fire
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 106: illegal multibyte sequence
[Server] [23:50:48] [Server thread/INFO]: There are 0 of a max of 20 players online:
Exception in thread Thread-79 (on_player_left):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\HibernateR.v1.2.0.mcdr\hibernate_r\__init__.py", line 98, in on_player_left
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 106: illegal multibyte sequence

**Comment by HIM049** [comment]
你使用的文本编辑器貌似使用了 GBK 编码配置文件。注意一下编辑器的编码设置需要为 UTF8，或者不要使用 windows 自带记事本编辑配置文件。
删除配置文件后重新生成即可。

**Comment by JoKerTanser** [comment]
> 你使用的文本编辑器貌似使用了 GBK 编码配置文件。注意一下编辑器的编码设置需要为 UTF8，或者不要使用 windows 自带记事本编辑配置文件。
> 删除配置文件后重新生成即可。

感谢🙏，我试一下
