### ISSUE TITLE
Exception in thread Thread-80

### ISSUE THREAD

**Issue by JoKerTanser** [HIM049/MCDR_HibernateR#7]
Exception in thread Thread-83 (check_config_fire):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\HibernateR.v1.2.0.mcdr\hibernate_r\__init__.py", line 263, in check_config_fire
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 106: illegal multibyte sequence
Exception in thread Thread-82 (hr_sleep):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 29, in wrapped_target
    raise e from None
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\new_thread.py", line 26, in wrapped_target
    self.__return_value = target(*args_, **kwargs_)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\HibernateR.v1.2.0.mcdr\hibernate_r\__init__.py", line 51, in hr_sleep
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\api\decorator\spam_proof.py", line 82, in wrap
    func(*args, **kwargs)
  File "plugins\HibernateR.v1.2.0.mcdr\hibernate_r\__init__.py", line 149, in fake_server
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x81 in position 106: illegal multibyte sequence

**Comment by sout233** [comment]
该issue疑似与#6 重复，将被close
